const beautify = require("js-beautify").js;

const { processAPIFile } = require("./processFunctions");
function generateRoute(func) {
    let full = func.raw + '\n';
    if (func.args.length > 0) {
        return full + `app.post('/${func.name}', (req, res) => {
    const body = req.body;
    const response = ${func.name}(${func.args.map(a => `body.${a}`).join(', ')});
    if(__isPromise(response)){
        response.then(r => res.send(JSON.stringify(r)));
    }else{
        res.send(JSON.stringify(response));
    }
});`;
    } else {
        return full + `app.get('/${func.name}', (req, res) => {
    const response = ${func.name}();
    if(__isPromise(response)){
        response.then(r => res.send(JSON.stringify(r)));
    }else{
        res.send(JSON.stringify(response));
    }
});`
    }
}

function generatePackageJson(packages) {
    return {
        name: "generator-js",
        version: "1.0.0",
        description: "",
        main: "index.js",
        scripts: {
            "test": "echo \"Error: no test specified\" && exit 1"
        },
        author: "",
        license: "ISC",
        dependencies: packages
    }
}

module.exports = function generateExpress(raw, functions, packages) {
    let response = `/*This is an automatic API generated by Automatique (https://automatique.dev)\n Generated ${new Date()}*/\nconst express = require('express');\nconst app = express();\n`
    packages.express = '^4';
    const processed = processAPIFile(raw, functions);
    const allGet = processed.functions.every(f => f.args.length === 0);
    if (!allGet) {
        response += "const bodyParser = require('body-parser');\n app.use(bodyParser.json());\n";
        packages['body-parser'] = "latest"
    }
    // Promise detection library, used in API calls
    response += "\nfunction __isPromise(obj){return !!obj && (typeof obj === 'object' || typeof obj === 'function') && typeof obj.then === 'function';}"
    response += "\n/*User-Declared `require` statements, non-public functions, globally scoped variables*/\n" + processed.initializer + "\n\n";
    return {
        index: beautify(response + "/*Public routes based on the open APIs are declared below*/\n" +
            processed.functions.map(m => generateRoute(m)).join('\n\n') +
            "\n\napp.listen(3000, () => console.log('example app listening at http://localhost:3000'))"),
        package: JSON.stringify(generatePackageJson(packages), null, 2)
    }
}