export interface packages {
  [propName: string]: string;
}
export interface functions {
  [funName: string]: {
    api: boolean;
    discovered?: boolean;
  };
}

export const getHeader = () =>
  `/*This is an automatic API generated by Automatique (https://automatique.dev)
Generated ${new Date()}*/\n`;
